sonar.projectKey=welbinator_form-handler-wp
sonar.organization=welbinator
sonar.projectName=Form Handler WP
sonar.projectVersion=1.3.0

# Source
sonar.sources=.
sonar.exclusions=vendor/**,node_modules/**,tests/**,*.min.js

# Tests
sonar.tests=tests
sonar.test.inclusions=tests/**/*Test.php

# PHP
sonar.php.version=7.4
