<?php

declare(strict_types=1);

/**
 * Acceptance tester actor.
 * Generated by Codeception — do not edit manually.
 * Run `vendor/bin/codecept build` to regenerate.
 */
class AcceptanceTester extends \Codeception\Actor
{
	use _generated\AcceptanceTesterActions;
}
